# Generated by Django 4.2.7 on 2025-01-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetapp', '0003_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Post',
        ),
    ]
